name: Track and Report on Python Application Timing and Complexity

on:
  pull_request:
  push:

jobs:
  wily:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2-beta
        with:
          fetch-depth: 0

      - uses: actions/checkout@v2-beta
        with:
          ref: refs/heads/master
          clean: false

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install wily

      - name: Build wily
        run: |
          wily build pitop/ pitopcli/ .

      - name: Print config, list all analysed revisions and operators used
        run: |
          wily index

      - name: Show metrics differences since master
        # Useful for PRs
        run: |
          wily diff --detail --revision master .

      - name: Show wily report for all files
        # Useful for overall review
        run: |
          for f in $(find . -name "*.py"); do
            file="${f#"./"}"
            dir="$(dirname ${file})"
            mkdir -p "reports/${dir}"
            wily report "${file}" -o reports/"${file%".py"}.html"
          done

      - name: Show wily rank
        run: |
          wily rank .
